import Head from "next/head"
import {FC} from "react"

import Link from "../../."
import styles from "../styles/Home.module.css"

const Home: FC = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Welcome to <Link to="https://nextjs.org">Next.js!</Link>
                </h1>

                <p className={styles.description}>
                    This is the home page. Check out the{" "}
                    <Link to="/about">about</Link> page.
                </p>
            </main>
        </div>
    )
}

export default Home
